name: Ca lint à balle par chez vous

on:
 push:
  branches: [main]

jobs:
  Ca-lint-a-balle-par-chez-vous:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Installation des dépendances
        run: yarn --cwd ./front
      - name: Lintage
        run: yarn --cwd ./front eslint ./front --ext .js

